import { Product, Order, Customer, Coupon } from "./types";

const now = new Date();
const iso = (d: Date) => d.toISOString();
const inHours = (h: number) => iso(new Date(now.getTime() + h * 3600 * 1000));
const daysAgo = (d: number) => iso(new Date(now.getTime() - d * 24 * 3600 * 1000));

export const CATEGORIAS = [
  "Celulares",
  "Notebooks",
  "Audio",
  "Gaming",
  "Accesorios",
  "Smart Home",
  "Televisores",
];

export const seedProducts: Product[] = [
  {
    id: "p1",
    titulo: "iPhone 15 128GB",
    categoria: "Celulares",
    descripcion:
      "iPhone 15 con chip A16 Bionic, cámara dual de 48MP y pantalla Super Retina XDR de 6.1\". Ideal para fotografía y rendimiento todo el día.",
    caracteristicas: ["Chip A16 Bionic", "Cámara 48MP", "Pantalla 6.1\" OLED", "USB-C"],
    precio: 1450000,
    precioOferta: 1290000,
    ofertaHasta: inHours(30),
    imagen: "https://images.unsplash.com/photo-1592286927505-1def25115558?w=800&q=80",
    stock: 14,
    stockMinimo: 5,
    variantes: [
      { id: "v1", nombre: "128GB - Negro", stock: 8 },
      { id: "v2", nombre: "128GB - Azul", stock: 6 },
    ],
    garantiaMeses: 12,
    sku: "CEL-IP15-128",
    status: "activo",
    vendidos: 37,
    creadoEn: daysAgo(20),
    likes: 128,
    guardados: 42,
    compartidos: 19,
    vistas: 980,
  },
  {
    id: "p2",
    titulo: "Notebook Lenovo IdeaPad 15.6\"",
    categoria: "Notebooks",
    descripcion:
      "Notebook ideal para trabajo y estudio. Intel Core i5, 16GB RAM, 512GB SSD. Rápida, liviana y con batería de larga duración.",
    caracteristicas: ["Intel Core i5", "16GB RAM", "512GB SSD", "Pantalla 15.6\" FHD"],
    precio: 980000,
    imagen: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80",
    stock: 3,
    stockMinimo: 4,
    garantiaMeses: 12,
    sku: "NB-LEN-IP156",
    status: "activo",
    vendidos: 21,
    creadoEn: daysAgo(45),
    likes: 64,
    guardados: 31,
    compartidos: 8,
    vistas: 512,
  },
  {
    id: "p3",
    titulo: "Auriculares Sony WH-1000XM5",
    categoria: "Audio",
    descripcion:
      "Auriculares inalámbricos con la mejor cancelación de ruido del mercado. 30hs de batería y sonido de altísima fidelidad.",
    caracteristicas: ["Cancelación de ruido líder", "30hs de batería", "Bluetooth 5.2", "Multipunto"],
    precio: 420000,
    precioOferta: 359000,
    ofertaHasta: inHours(6),
    imagen: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80",
    stock: 22,
    stockMinimo: 5,
    variantes: [
      { id: "v1", nombre: "Negro", stock: 12 },
      { id: "v2", nombre: "Plata", stock: 10 },
    ],
    garantiaMeses: 12,
    sku: "AUD-SNY-XM5",
    status: "activo",
    vendidos: 58,
    creadoEn: daysAgo(10),
    likes: 210,
    guardados: 77,
    compartidos: 34,
    vistas: 1420,
  },
  {
    id: "p4",
    titulo: "PlayStation 5 Slim",
    categoria: "Gaming",
    descripcion:
      "Consola de última generación con SSD ultra rápido, gráficos en 4K y control DualSense con feedback háptico.",
    caracteristicas: ["1TB SSD", "4K a 120fps", "DualSense incluido", "Retrocompatible"],
    precio: 1150000,
    imagen: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&q=80",
    stock: 2,
    stockMinimo: 3,
    garantiaMeses: 12,
    sku: "GAM-PS5-SLIM",
    status: "activo",
    vendidos: 44,
    creadoEn: daysAgo(60),
    likes: 301,
    guardados: 120,
    compartidos: 51,
    vistas: 2100,
  },
  {
    id: "p5",
    titulo: "Smartwatch Xiaomi Watch S3",
    categoria: "Accesorios",
    descripcion:
      "Reloj inteligente con GPS, monitor de oxígeno y ritmo cardíaco, y hasta 15 días de batería. Resistente al agua.",
    caracteristicas: ["GPS integrado", "15 días de batería", "Resistente al agua 5ATM", "+150 modos deportivos"],
    precio: 180000,
    imagen: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
    stock: 31,
    stockMinimo: 8,
    garantiaMeses: 6,
    sku: "ACC-XIA-WS3",
    status: "activo",
    vendidos: 15,
    creadoEn: daysAgo(5),
    likes: 45,
    guardados: 18,
    compartidos: 4,
    vistas: 340,
  },
  {
    id: "p6",
    titulo: "Smart TV Samsung 55\" 4K",
    categoria: "Televisores",
    descripcion:
      "Televisor 4K UHD con HDR, Tizen OS y Google Assistant integrado. Imagen nítida y colores vibrantes.",
    caracteristicas: ["4K UHD HDR10+", "Tizen Smart TV", "3x HDMI 2.1", "Google Assistant"],
    precio: 890000,
    precioOferta: 799000,
    ofertaHasta: inHours(50),
    imagen: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80",
    stock: 6,
    stockMinimo: 3,
    garantiaMeses: 24,
    sku: "TV-SAM-55-4K",
    status: "activo",
    vendidos: 9,
    creadoEn: daysAgo(15),
    likes: 88,
    guardados: 40,
    compartidos: 12,
    vistas: 610,
  },
  {
    id: "p7",
    titulo: "Parlante JBL Charge 5",
    categoria: "Audio",
    descripcion:
      "Parlante portátil resistente al agua (IP67) con 20hs de batería y sonido potente para cualquier lugar.",
    caracteristicas: ["IP67 sumergible", "20hs de batería", "Power Bank integrado", "Bluetooth 5.1"],
    precio: 260000,
    imagen: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80",
    stock: 0,
    stockMinimo: 5,
    garantiaMeses: 12,
    sku: "AUD-JBL-CH5",
    status: "agotado",
    vendidos: 63,
    creadoEn: daysAgo(80),
    likes: 156,
    guardados: 60,
    compartidos: 22,
    vistas: 900,
  },
  {
    id: "p8",
    titulo: "Cámara de seguridad WiFi 360°",
    categoria: "Smart Home",
    descripcion:
      "Cámara inteligente con visión nocturna, detección de movimiento y monitoreo en vivo desde el celular.",
    caracteristicas: ["Visión 360°", "Visión nocturna", "Detección de movimiento", "App gratuita"],
    precio: 65000,
    imagen: "https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?w=800&q=80",
    stock: 40,
    stockMinimo: 10,
    garantiaMeses: 6,
    sku: "HOME-CAM-360",
    status: "activo",
    vendidos: 27,
    creadoEn: daysAgo(3),
    likes: 33,
    guardados: 14,
    compartidos: 3,
    vistas: 280,
  },
];

export const seedCustomers: Customer[] = [
  {
    id: "c1",
    nombre: "Martina Gómez",
    telefono: "+54 9 11 5555-0101",
    email: "martina@example.com",
    totalComprado: 1450000,
    cantidadPedidos: 3,
    deuda: 0,
    ultimaCompra: daysAgo(4),
    esRecurrente: true,
    productosGuardados: ["p2", "p6"],
    productosLikeados: ["p1", "p2", "p6", "p3"],
    scoreInteres: 82,
  },
  {
    id: "c2",
    nombre: "Facundo Álvarez",
    telefono: "+54 9 11 5555-0102",
    totalComprado: 359000,
    cantidadPedidos: 1,
    deuda: 120000,
    ultimaCompra: daysAgo(12),
    esRecurrente: false,
    productosGuardados: ["p4"],
    productosLikeados: ["p4", "p3"],
    scoreInteres: 65,
  },
  {
    id: "c3",
    nombre: "Rocío Fernández",
    telefono: "+54 9 11 5555-0103",
    email: "rocio@example.com",
    totalComprado: 2600000,
    cantidadPedidos: 6,
    deuda: 0,
    ultimaCompra: daysAgo(1),
    esRecurrente: true,
    productosGuardados: ["p1"],
    productosLikeados: ["p1", "p5", "p8"],
    scoreInteres: 91,
  },
  {
    id: "c4",
    nombre: "Nicolás Torres",
    telefono: "+54 9 11 5555-0104",
    totalComprado: 0,
    cantidadPedidos: 0,
    deuda: 0,
    esRecurrente: false,
    productosGuardados: ["p4", "p6", "p1"],
    productosLikeados: ["p4", "p6", "p1", "p3", "p2"],
    scoreInteres: 88,
  },
];

export const seedOrders: Order[] = [
  {
    id: "o1001",
    cliente: { nombre: "Martina Gómez", telefono: "+54 9 11 5555-0101" },
    items: [
      { productId: "p3", titulo: "Auriculares Sony WH-1000XM5", variante: "Negro", cantidad: 1, precioUnitario: 359000, imagen: seedProducts[2].imagen },
    ],
    total: 359000,
    entrega: "envio",
    direccion: "Av. Corrientes 1234, CABA",
    metodoPago: "mercadopago",
    status: "en_camino",
    creadoEn: daysAgo(1),
  },
  {
    id: "o1000",
    cliente: { nombre: "Facundo Álvarez", telefono: "+54 9 11 5555-0102" },
    items: [
      { productId: "p4", titulo: "PlayStation 5 Slim", cantidad: 1, precioUnitario: 1150000, imagen: seedProducts[3].imagen },
    ],
    total: 1150000,
    entrega: "retiro",
    metodoPago: "transferencia",
    status: "pendiente",
    creadoEn: daysAgo(0),
    notas: "Cliente con saldo pendiente de compra anterior",
  },
  {
    id: "o0999",
    cliente: { nombre: "Rocío Fernández", telefono: "+54 9 11 5555-0103" },
    items: [
      { productId: "p1", titulo: "iPhone 15 128GB", variante: "128GB - Azul", cantidad: 1, precioUnitario: 1290000, imagen: seedProducts[0].imagen },
    ],
    total: 1290000,
    entrega: "envio",
    direccion: "Av. Rivadavia 5000, CABA",
    metodoPago: "mercadopago",
    status: "entregado",
    creadoEn: daysAgo(3),
  },
];

export const seedCoupons: Coupon[] = [
  { id: "cp1", codigo: "BIENVENIDO10", tipo: "porcentaje", valor: 10, activo: true, usosActuales: 34 },
  { id: "cp2", codigo: "ENVIOGRATIS", tipo: "monto_fijo", valor: 8000, activo: true, usosActuales: 12 },
];
